# Generated by Django 5.0.6 on 2024-06-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaEntrega', models.DateField()),
                ('entregado', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Curso',
            new_name='AcerdaDeMi',
        ),
        migrations.RenameModel(
            old_name='Entregable',
            new_name='Contacto',
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Cv',
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='EstudiosHabilidades',
        ),
    ]
