# Generated by Django 5.0.6 on 2024-06-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_portfolio_rename_curso_acerdademi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('institucion', models.CharField(max_length=50)),
                ('añoFin', models.DateField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='EstudiosHabilidades',
        ),
    ]
