# Generated by Django 5.0.6 on 2024-06-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_estudios_delete_estudioshabilidades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudios',
            old_name='añoFin',
            new_name='anio',
        ),
    ]
