# Generated by Django 5.0.6 on 2024-07-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_rename_empresa_experiencia_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='fin',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='inicio',
            field=models.CharField(max_length=10),
        ),
    ]
