# Generated by Django 5.0.6 on 2024-07-02 23:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_alter_experiencia_fin_alter_experiencia_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudios',
            name='descripciones',
            field=models.TextField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudios',
            name='anio',
            field=models.CharField(max_length=10),
        ),
    ]
