# Generated by Django 5.0.6 on 2024-07-02 23:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_estudios_descripciones_alter_estudios_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudios',
            name='degree',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='anioProyecto',
            field=models.CharField(max_length=10),
        ),
    ]
