# Generated by Django 5.0.6 on 2024-07-03 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_estudios_degree_alter_proyectos_anioproyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectos',
            old_name='anioProyecto',
            new_name='anioproyecto',
        ),
        migrations.RenameField(
            model_name='proyectos',
            old_name='descripcion',
            new_name='descripcionproyecto',
        ),
        migrations.RenameField(
            model_name='proyectos',
            old_name='nombreProyecto',
            new_name='nombreproyecto',
        ),
        migrations.RemoveField(
            model_name='estudios',
            name='descripciones',
        ),
    ]
