# Generated by Django 5.0.6 on 2024-07-03 00:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_rename_anioproyecto_proyectos_anioproyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='proyectoimg',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
