# Generated by Django 5.0.6 on 2024-07-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_proyectos_proyectoimg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactoCliente',
            new_name='Contacto',
        ),
    ]
