# Generated by Django 5.0.6 on 2024-07-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_rename_contactocliente_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.CharField(max_length=300),
        ),
    ]
