# Generated by Django 5.0.6 on 2024-07-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_alter_contacto_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='descripcionproyecto',
            field=models.CharField(max_length=300),
        ),
    ]
