# Generated by Django 5.0.6 on 2024-07-04 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_alter_proyectos_descripcionproyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectos',
            old_name='anioproyecto',
            new_name='fechaproyecto',
        ),
    ]
